#ChingMaoJin_22013213
#Name: Ching Mao Jin
#StudentID: 22013213
#Database System 2024 Sem2
-- Inserting values into Team table

INSERT INTO Team(Team_ID,Country,Team_Name,Coach_Name,Sport)VALUES
(1001,'MY','TeamMY','John Doe','clout shooting'),
(1002,'MY','TeamMY','Jane Smith','field archery'),
(1003,'MY','TeamMY','Mike Brown','flight shooting'),
(1004,'MY','TeamMY','Emily White','kyūdō'),
(1005,'MY','TeamMY','Chris Green','roving'),
(1006,'MY','TeamMY','Sarah Black','association croquet'),
(1007,'MY','TeamMY','James Blue','badminton'),
(1008,'MY','TeamMY','Anna Grey','biathlon'),
(1009,'MY','TeamMY','David Red','birling'),
(1010,'MY','TeamMY','Olivia Pink','boccie'),
(1011,'MY','TeamMY','Daniel Yellow','bodybuilding'),
(1012,'MY','TeamMY','Mia Purple','boules'),
(1013,'MY','TeamMY','Liam Orange','bowling'),
(1014,'MY','TeamMY','Ava Brown','candlepins'),
(1015,'MY','TeamMY','Noah Silver','cocked hat'),
(1016,'MY','TeamMY','Sophia Gold','duckpins'),
(1017,'MY','TeamMY','Lucas Teal','ninepins'),
(1018,'MY','TeamMY','Isabella Coral','skittles'),
(1019,'MY','TeamMY','Ethan Indigo','bowls'),
(1020,'MY','TeamMY','Charlotte Lime','boxing'),
(1021,'MY','TeamMY','Jackson Olive','croquet'),
(1022,'MY','TeamMY','Amelia Mint','cross-country'),
(1023,'MY','TeamMY','Aiden Cherry','darts'),
(1024,'MY','TeamMY','Harper Plum','deck tennis'),
(1025,'MY','TeamMY','Samuel Maroon','diving'),
(1026,'MY','TeamMY','Mason Beige','fencing'),
(1027,'MY','TeamMY','Ella Cyan','kendo'),
(1028,'MY','TeamMY','Henry Magenta','golf'),
(1029,'MY','TeamMY','Victoria Peach','gymnastics'),
(1030,'MY','TeamMY','Logan Tan','balance beam'),
(1031,'MY','TeamMY','Aria Gray','floor exercise'),
(1032,'MY','TeamMY','Owen Salmon','horizontal bar'),
(1033,'MY','TeamMY','Scarlett Lavender','parallel bars'),
(1034,'MY','TeamMY','Maverick Raspberry','pommel horse'),
(1035,'MY','TeamMY','Ella Rose','rhythmic gymnastics'),
(1036,'MY','TeamMY','Daniel Mint','rings'),
(1037,'MY','TeamMY','Hannah Amber','uneven parallel bars'),
(1038,'MY','TeamMY','Wyatt Aquamarine','vaulting'),
(1039,'MY','TeamMY','Layla Pearl','handball'),
(1040,'MY','TeamMY','Sebastian Steel','horseshoe pitching'),
(1041,'MY','TeamMY','Zoe Bronze','jai alai'),
(1042,'MY','TeamMY','Gavin Black','martial arts'),
(1043,'MY','TeamMY','Chloe White','aikido'),
(1044,'MY','TeamMY','Elijah Indigo','capoeira'),
(1045,'MY','TeamMY','Grace Golden','hapkido'),
(1046,'MY','TeamMY','Carter Violet','judo'),
(1047,'MY','TeamMY','Addison Burgundy','jujitsu'),
(1048,'MY','TeamMY','Landon Chartreuse','karate'),
(1049,'MY','TeamMY','Lucy Salmon','kendō'),
(1050,'AUS','TeamAUS','Lincoln Olive','kung fu'),
(1051,'AUS','TeamAUS','Natalie Chocolate','pankration'),
(1052,'AUS','TeamAUS','Austin Cyan','savate'),
(1053,'AUS','TeamAUS','Ellie Gray','tai chi chuan'),
(1054,'AUS','TeamAUS','Brayden Purple','tae kwon do'),
(1055,'AUS','TeamAUS','Nora Tangerine','mountaineering'),
(1056,'AUS','TeamAUS','Gabriel Coral','orienteering'),
(1057,'AUS','TeamAUS','Madison Mint','pall-mall'),
(1058,'AUS','TeamAUS','Hunter Magenta','pelota'),
(1059,'AUS','TeamAUS','Samantha Lime','pentathlon'),
(1060,'AUS','TeamAUS','Colton Teal','quoits'),
(1061,'AUS','TeamAUS','Peyton Gold','rackets'),
(1062,'AUS','TeamAUS','Nicholas Pink','racquetball'),
(1063,'AUS','TeamAUS','Alyssa Beige','real tennis'),
(1064,'AUS','TeamAUS','Dylan Orange','shooting'),
(1065,'AUS','TeamAUS','Mila Blue','skeet shooting'),
(1066,'AUS','TeamAUS','Zachary Coral','trapshooting'),
(1067,'AUS','TeamAUS','Cora Indigo','shuffleboard'),
(1068,'AUS','TeamAUS','Nathan Purple','skating'),
(1069,'AUS','TeamAUS','Victoria Gray','ice skating'),
(1070,'AUS','TeamAUS','Harrison Tan','figure skating'),
(1071,'AUS','TeamAUS','Madeline Raspberry','speed skating'),
(1072,'AUS','TeamAUS','Ian Salmon','short-track speed skating'),
(1073,'AUS','TeamAUS','Penelope White','roller-skating'),
(1074,'AUS','TeamAUS','Dominic Magenta','skibobbing'),
(1075,'AUS','TeamAUS','Aurora Lavender','skiing'),
(1076,'AUS','TeamAUS','Julian Beige','Alpine skiing'),
(1077,'AUS','TeamAUS','Bella Cyan','downhill skiing'),
(1078,'AUS','TeamAUS','Thomas Coral','slalom'),
(1079,'AUS','TeamAUS','Natalia Plum','freestyle skiing'),
(1080,'AUS','TeamAUS','Leo Gray','Nordic skiing'),
(1081,'AUS','TeamAUS','Lila Gold','cross-country skiing'),
(1082,'AUS','TeamAUS','Xavier Brown','ski jumping'),
(1083,'AUS','TeamAUS','Riley Pink','speed skiing'),
(1084,'AUS','TeamAUS','Brandon Orange','waterskiing'),
(1085,'AUS','TeamAUS','Addison Lime','snowboarding'),
(1086,'AUS','TeamAUS','Aiden Teal','squash rackets'),
(1087,'USA','TeamUSA','Claire Violet','squash tennis'),
(1088,'USA','TeamUSA','Logan Indigo','swimming'),
(1089,'USA','TeamUSA','Eva Coral','synchronized swimming'),
(1090,'USA','TeamUSA','Isaiah Purple','tennis'),
(1091,'USA','TeamUSA','Daphne Tan','paddle tennis'),
(1092,'USA','TeamUSA','Jason Blue','table tennis'),
(1093,'USA','TeamUSA','Sophie Mint','track-and-field sports/athletics'),
(1094,'USA','TeamUSA','Caleb Gray','decathlon'),
(1095,'USA','TeamUSA','Lily Burgundy','discus throw'),
(1096,'USA','TeamUSA','Tyler Olive','hammer throw'),
(1097,'USA','TeamUSA','Julia Golden','heptathlon'),
(1098,'USA','TeamUSA','Adrian Black','high jump'),
(1099,'USA','TeamUSA','Nina Lavender','javelin throw'),
(1100,'USA','TeamUSA','Gavin Coral','long jump'),
(1101,'USA','TeamUSA','Yamileth Mena','pole vault'),
(1102,'USA','TeamUSA','Jaylen Connelly','running'),
(1103,'USA','TeamUSA','Aaliyah Coronado','hurdling'),
(1104,'USA','TeamUSA','Sequoia Stanley','long-distance running'),
(1105,'USA','TeamUSA','Ramiro Slocum','marathon'),
(1106,'USA','TeamUSA','Valeria Cullen','middle-distance running'),
(1107,'USA','TeamUSA','Kami Richey','sprint'),
(1108,'USA','TeamUSA','Cherokee Whitley','steeplechase'),
(1109,'USA','TeamUSA','Yosef Cline','shot put'),
(1110,'USA','TeamUSA','Charlie Andersen','triple jump'),
(1111,'USA','TeamUSA','Gunner Lott','triathlon'),
(1112,'USA','TeamUSA','Chyanne Vergara','underwater diving'),
(1113,'USA','TeamUSA','Brennen Sample','weightlifting'),
(1114,'USA','TeamUSA','Harold Helton','powerlifting'),
(1115,'USA','TeamUSA','Carley Stock','weight throw'),
(1116,'USA','TeamUSA','Jorge Heim','wrestling'),
(1117,'USA','TeamUSA','Nelly Hillman','catch-as-catch-can wrestling'),
(1118,'USA','TeamUSA','Russell Paredes','Cornish wrestling'),
(1119,'USA','TeamUSA','Dalila Neely','Cumberland wrestling'),
(1120,'USA','TeamUSA','Damon Pearson','freestyle wrestling'),
(1121,'USA','TeamUSA','Caley Aviles','Greco-Roman wrestling'),
(1122,'USA','TeamUSA','Treyton Ott','sambo'),
(1123,'USA','TeamUSA','Paxton Eddy','Schwingen'),
(1124,'USA','TeamUSA','Erica Villarreal','sumo'),
(1125,'USA','TeamUSA','London Colon','archery'),
(1126,'USA','TeamUSA','Darwin Julian','association croquet'),
(1127,'USA','TeamUSA','Shira Zeigler','badminton'),
(1128,'USA','TeamUSA','Jayden Madrid','bandy'),
(1129,'USA','TeamUSA','Lillie Lim','baseball'),
(1130,'USA','TeamUSA','Deangelo Dell','basketball'),
(1131,'USA','TeamUSA','Tyrek Workman','biathlon'),
(1132,'USA','TeamUSA','Whitney Haas','boccie'),
(1133,'USA','TeamUSA','Joselin Forte','boules'),
(1134,'USA','TeamUSA','Yolanda Moulton','bowling'),
(1135,'USA','TeamUSA','Tristan Maas','candlepins'),
(1136,'USA','TeamUSA','Ryley Perez','cocked hat'),
(1137,'USA','TeamUSA','Jennifer Waller','duckpins'),
(1138,'USA','TeamUSA','Dakota Luciano','bowls'),
(1139,'USA','TeamUSA','Connor Forman','cricket'),
(1140,'USA','TeamUSA','Jamie Grice','Twenty20 cricket'),
(1141,'USA','TeamUSA','Alejandro Han','croquet'),
(1142,'USA','TeamUSA','Sunny Crabtree','cross-country'),
(1143,'USA','TeamUSA','Cayden Kirk','curling'),
(1144,'USA','TeamUSA','Adonis Bassett','darts'),
(1145,'USA','TeamUSA','Keaton Murry','deck tennis'),
(1146,'USA','TeamUSA','Kiera Fisk','Eisstockschiessen'),
(1147,'USA','TeamUSA','Blaise Muir','field hockey'),
(1148,'USA','TeamUSA','Kalen Riggs','fives'),
(1149,'USA','TeamUSA','Saul Masterson','football'),
(1150,'USA','TeamUSA','John Powell','Australian rules football'),
(1151,'USA','TeamUSA','Lizet Emerson','football (soccer)'),
(1152,'USA','TeamUSA','Domenic Rucker','Gaelic football'),
(1153,'USA','TeamUSA','Joslyn Lunsford','gridiron football'),
(1154,'USA','TeamUSA','Shekinah Gilchrist','rugby'),
(1155,'USA','TeamUSA','Kallie Delacruz','gymnastics'),
(1156,'USA','TeamUSA','Casey Havens','rhythmic gymnastics'),
(1157,'USA','TeamUSA','Alexandre Rao','handball'),
(1158,'USA','TeamUSA','Bridgett Alvarez','Hooverball'),
(1159,'USA','TeamUSA','Danae Morrison','horseshoe pitching'),
(1160,'USA','TeamUSA','Jeanette Robison','hurling'),
(1161,'USA','TeamUSA','Kelsea Hein','ice hockey'),
(1162,'USA','TeamUSA','Demetria Villalobos','jai alai'),
(1163,'USA','TeamUSA','Sean Spivey','kabaddi'),
(1164,'USA','TeamUSA','Trae Delgadillo','korfball'),
(1165,'USA','TeamUSA','Tomas Horowitz','lacrosse'),
(1166,'USA','TeamUSA','Byron Vazquez','box lacrosse'),
(1167,'USA','TeamUSA','Brennon Levesque','netball'),
(1168,'USA','TeamUSA','Corrine Haase','orienteering'),
(1169,'UK','TeamUK','Matteo Donovan','pelota'),
(1170,'UK','TeamUK','Robert Weiss','rackets'),
(1171,'UK','TeamUK','Callie McClellan','racquetball'),
(1172,'UK','TeamUK','Giselle Rincon','real tennis'),
(1173,'UK','TeamUK','Elliott Sanders','rounders'),
(1174,'UK','TeamUK','Xochitl Clapp','skating'),
(1175,'UK','TeamUK','Marlon Briones','figure skating'),
(1176,'UK','TeamUK','Derek Shepherd','roller-skating'),
(1177,'UK','TeamUK','Tyrek Frost','speed skating'),
(1178,'UK','TeamUK','Jamar Byrne','skiing'),
(1179,'UK','TeamUK','Ronald Meza','Nordic skiing'),
(1180,'UK','TeamUK','Stone Hays','cross-country skiing'),
(1181,'UK','TeamUK','Joaquin Falcon','shinty'),
(1182,'UK','TeamUK','Jaylen Crocker','shuffleboard'),
(1183,'UK','TeamUK','Mika Hanlon','softball'),
(1184,'UK','TeamUK','Destiney Calderon','squash rackets'),
(1185,'UK','TeamUK','Shelton Nadeau','swimming'),
(1186,'UK','TeamUK','Monika McManus','synchronized swimming'),
(1187,'UK','TeamUK','Mikael Machado','table tennis'),
(1188,'UK','TeamUK','Gracie Neely','team handball'),
(1189,'UK','TeamUK','Aimee Clifton','tennis'),
(1190,'UK','TeamUK','Jimmie Haggerty','paddle tennis'),
(1191,'UK','TeamUK','Ray Neal','table tennis'),
(1192,'UK','TeamUK','Jaiden Watson','track-and-field'),
(1193,'UK','TeamUK','Carlee Nance','running'),
(1194,'UK','TeamUK','Will Heaton','relay race'),
(1195,'UK','TeamUK','Leandra Conner','triathlon'),
(1196,'UK','TeamUK','Andie Jansen','tug-of-war'),
(1197,'UK','TeamUK','Shea Lea','volleyball'),
(1198,'UK','TeamUK','Nestor Sewell','water polo'),
(1199,'UK','TeamUK','Luc Gross','Diving'),
(1200,'UK','TeamUK','Cristobal Mathis','basketball'),
(1201,'UK','TeamUK','Beverly Parnell','aerobatics'),
(1202,'UK','TeamUK','Paige Herzog','air racing'),
(1203,'UK','TeamUK','Bradley Mello','automobile racing'),
(1204,'UK','TeamUK','Victoria Sawyer','drag racing'),
(1205,'UK','TeamUK','Ananda Mathew','Grand Prix racing'),
(1206,'UK','TeamUK','Lyndsay Bello','gymkhana'),
(1207,'UK','TeamUK','Edward Gillette','hill climb'),
(1208,'UK','TeamUK','Isabella Popp','karting'),
(1209,'UK','TeamUK','Yasmine Prather','midget-car racing'),
(1210,'UK','TeamUK','Emily Lea','offroad racing'),
(1211,'UK','TeamUK','Stacie Albert','rally'),
(1212,'UK','TeamUK','Mariela Eller','speedway racing'),
(1213,'UK','TeamUK','Immanuel Johnson','sports-car racing'),
(1214,'UK','TeamUK','Katy Carl','stock-car racing'),
(1215,'UK','TeamUK','Kade Swafford','ballooning'),
(1216,'UK','TeamUK','Garrett Pool','bullfighting'),
(1217,'UK','TeamUK','Daijah Messer','rejoneo'),
(1218,'UK','TeamUK','Alysa Donnelly','bungee jumping'),
(1219,'UK','TeamUK','Yasmeen Dow','camel racing'),
(1220,'UK','TeamUK','Janna Marin','canoeing'),
(1221,'UK','TeamUK','Rita Villasenor','wild-water racing'),
(1222,'NZ','TeamNZ','Dale Connor','cockfighting'),
(1223,'NZ','TeamNZ','Tylor Sikes','cycling'),
(1224,'NZ','TeamNZ','Jill Custer','cycle ball'),
(1225,'NZ','TeamNZ','Emanuel Castellanos','cyclo-cross'),
(1226,'NZ','TeamNZ','Brian Ray','motor-paced race'),
(1227,'NZ','TeamNZ','Xavier Merriman','pursuit racing'),
(1228,'NZ','TeamNZ','Leonel Bowser','road race'),
(1229,'NZ','TeamNZ','Waylon Gibson','pursuit racing'),
(1230,'NZ','TeamNZ','Wilson Parris','road race'),
(1231,'NZ','TeamNZ','Kameron Liang','six-day race'),
(1232,'NZ','TeamNZ','Ashton Reyna','sprint'),
(1233,'NZ','TeamNZ','Charity Tompkins','dog racing'),
(1234,'NZ','TeamNZ','Guadalupe Wilcox','dogsled racing'),
(1235,'NZ','TeamNZ','Melia Lawson','fishing'),
(1236,'NZ','TeamNZ','Vicky Wellman','fly-fishing'),
(1237,'NZ','TeamNZ','Nayely Barton','gladiatorial sports'),
(1238,'NZ','TeamNZ','Candy Headley','venationes'),
(1239,'NZ','TeamNZ','Larissa Pruett','gliding'),
(1240,'NZ','TeamNZ','Sasha Marino','hang gliding'),
(1241,'NZ','TeamNZ','Earl Coughlin','paragliding'),
(1242,'NZ','TeamNZ','Sheyla Monroy','horsemanship'),
(1243,'CND','TeamCND','Emma Patton','buzkashī'),
(1244,'CND','TeamCND','Donnie Timmons','chariot racing'),
(1245,'CND','TeamCND','Parker Smart','dressage'),
(1246,'CND','TeamCND','Valerie Whittington','harness racing'),
(1247,'CND','TeamCND','Phoenix Edmonds','horse racing'),
(1248,'CND','TeamCND','Avery Redden','hurdle race'),
(1249,'CND','TeamCND','Jadyn Baum','joust'),
(1250,'CND','TeamCND','Benjamin Galbraith','point-to-point'),
(1251,'CND','TeamCND','Lamont Hamlin','quarter-horse racing'),
(1252,'CND','TeamCND','Stephany Redmond','show jumping'),
(1253,'CND','TeamCND','Esther Kang','steeplechase'),
(1254,'CND','TeamCND','Heidy Bock','hunting'),
(1255,'CND','TeamCND','Kobi Araujo','coursing'),
(1256,'CND','TeamCND','Cullen Gilmore','falconry'),
(1257,'CND','TeamCND','Kelsey Autry','field trial'),
(1258,'CND','TeamCND','Sam Cordell','foxhunting'),
(1259,'CND','TeamCND','Rodney Johns','iceboating'),
(1260,'CND','TeamCND','Morris Rao','motorcycle racing'),
(1261,'CND','TeamCND','Leanne Kelsey','motocross'),
(1262,'CND','TeamCND','Jefferson Kunz','motorcycle trial'),
(1263,'CND','TeamCND','Lizette Wilbur','motor-paced race'),
(1264,'CND','TeamCND','Carly Helm','offroad racing'),
(1265,'CND','TeamCND','Kristen Brinkman','speedway racing'),
(1266,'CND','TeamCND','Cody Gore','pigeon racing'),
(1267,'CND','TeamCND','Tyron Benedict','polo'),
(1268,'CND','TeamCND','Galen Joe','polocrosse'),
(1269,'CND','TeamCND','Angeles Hennessy','rodeo'),
(1270,'CND','TeamCND','Aliza Fugate','bareback bronc-riding'),
(1271,'CND','TeamCND','Antoinette Underwood','bull riding'),
(1272,'CND','TeamCND','Kyndall Hudson','calf roping'),
(1273,'CHN','TeamCHN','Randall Beal','steer roping'),
(1274,'CHN','TeamCHN','Saira Wirth','steer wrestling'),
(1275,'CHN','TeamCHN','Coleton Raines','team roping'),
(1276,'CHN','TeamCHN','Chaim Hillman','rowing'),
(1277,'CHN','TeamCHN','Jayden Dyson','skateboarding'),
(1278,'CHN','TeamCHN','Irma Goforth','skydiving'),
(1279,'CHN','TeamCHN','Daysha Hamlin','sledding'),
(1280,'CHN','TeamCHN','Sidney Hanley','bobsledding'),
(1281,'CHN','TeamCHN','Sergio Castle','lugeing'),
(1282,'CHN','TeamCHN','Zechariah Everhart','skeleton sledding'),
(1283,'CHN','TeamCHN','Nathen Hawks','tobogganing'),
(1284,'CHN','TeamCHN','Shelby Larue','surfing'),
(1285,'CHN','TeamCHN','Celina Darnell','windsurfing'),
(1286,'CHN','TeamCHN','Dorian Nance','tournament'),
(1287,'CHN','TeamCHN','Mohammad McGowan','mêlée'),
(1288,'CHN','TeamCHN','Theo Villareal','Badminton'),
(1289,'CHN','TeamCHN','Treyton Ely','Baseball 5'),
(1290,'CHN','TeamCHN','Tania Hendrix','Baseball Softball'),
(1291,'CHN','TeamCHN','Madilyn Danner','Basketball'),
(1292,'CHN','TeamCHN','Casandra Paquette','Basketball 3x3'),
(1293,'SG','TeamSG','Peyton Bohannon','Beach Handball'),
(1294,'SG','TeamSG','Louie Cable','Beach Volleyball'),
(1295,'SG','TeamSG','Mya Tubbs','Biathlon'),
(1296,'SG','TeamSG','Alivia Ridenour','Bobsleigh'),
(1297,'SG','TeamSG','Jazlynn Monson','Boxing'),
(1298,'SG','TeamSG','Oliver Tomlinson','Breaking'),
(1299,'SG','TeamSG','Kristi Walden','swimming'),
(1300,'SG','TeamSG','Noemi Henson','Badminton');