#ChingMaoJin_22013213
#Name: Ching Mao Jin
#StudentID: 22013213
#Database System 2024 Sem2
-- The name of athlete are randomly generated from this link -https://catonmat.net/tools/generate-random-names
-- The sports are taken from this link - https://www.britannica.com/topic/list-of-sports-2038581
#Inserting values into the Athlete tables

INSERT INTO Athlete(Athlete_ID,Athlete_Name,Gender,Sport,Competition_Type,Coach_Name,Country,Team_Name,Coach_ID,Age) VALUES
(400,'Ruth Solorzano','M','clout shooting','Individual','John Doe','MY','NULL',1,25),
(401,'Ben Carreon','M','field archery','Individual','Jane Smith','MY','NULL',2,14),
(402,'Maximus Hairston','M','flight shooting','Individual','Mike Brown','MY','NULL',3,31),
(403,'Jade Rankin','M','kyūdō','Individual','Emily White','MY','NULL',4,17),
(404,'Immanuel Burnette','M','roving','Individual','Chris Green','MY','NULL',5,33),
(405,'Xzavier Singleton','M','association croquet','Individual','Sarah Black','MY','NULL',6,26),
(406,'Bailey Billingsley','M','badminton','Individual','James Blue','MY','NULL',7,32),
(407,'Martin Swartz','M','biathlon','Individual','Anna Grey','MY','NULL',8,16),
(408,'Candy Gold','M','birling','Individual','David Red','MY','NULL',9,21),
(409,'Hans Spear','M','boccie','Individual','Olivia Pink','MY','NULL',10,31),
(410,'Cory Maier','M','bodybuilding','Individual','Daniel Yellow','MY','NULL',11,19),
(411,'Nehemiah Cooke','M','boules','Individual','Mia Purple','MY','NULL',12,22),
(412,'Maxim Wetzel','M','bowling','Individual','Liam Orange','MY','NULL',13,35),
(413,'Brian Blevins','M','candlepins','Individual','Ava Brown','MY','NULL',14,20),
(414,'Lisette Chappell','M','cocked hat','Individual','Noah Silver','MY','NULL',15,30),
(415,'Kyle Haywood','M','duckpins','Individual','Sophia Gold','MY','NULL',16,18),
(416,'Miriam Lauer','M','ninepins','Individual','Lucas Teal','MY','NULL',17,19),
(417,'Tyriq Biggs','M','skittles','Individual','Isabella Coral','MY','NULL',18,18),
(418,'Alanna Rodrigues','F','bowls','Individual','Ethan Indigo','MY','NULL',19,18),
(419,'Delanie Neill','F','boxing','Individual','Charlotte Lime','MY','NULL',20,31),
(420,'Michelle McCorkle','F','croquet','Individual','Jackson Olive','MY','NULL',21,15),
(421,'Yesenia Castle','F','cross-country','Individual','Amelia Mint','MY','NULL',22,26),
(422,'Jerimiah Fine','F','darts','Individual','Aiden Cherry','MY','NULL',23,28),
(423,'Lexie Dick','F','deck tennis','Individual','Harper Plum','MY','NULL',24,24),
(424,'Denis Ferguson','F','diving','Individual','Samuel Maroon','MY','NULL',25,26),
(425,'Antonia Magana','F','fencing','Individual','Mason Beige','MY','NULL',26,14),
(426,'Bryn Wofford','F','kendo','Individual','Ella Cyan','MY','NULL',27,23),
(427,'Bradley Harder','F','golf','Individual','Henry Magenta','MY','NULL',28,24),
(428,'Kameron Goodman','F','gymnastics','Individual','Victoria Peach','MY','NULL',29,23),
(429,'Mario McGuire','F','balance beam','Individual','Logan Tan','MY','NULL',30,20),
(430,'Jericho Costa','F','floor exercise','Individual','Aria Gray','MY','NULL',31,35),
(431,'Jefferson Hogan','F','horizontal bar','Individual','Owen Salmon','MY','NULL',32,33),
(432,'Katerina Gold','F','parallel bars','Individual','Scarlett Lavender','MY','NULL',33,33),
(433,'Breann Munson','F','pommel horse','Individual','Maverick Raspberry','MY','NULL',34,17),
(434,'Trever Sweet','F','rhythmic gymnastics','Individual','Ella Rose','MY','NULL',35,20),
(435,'Javen McPherson','F','rings','Individual','Daniel Mint','MY','NULL',36,16),
(436,'Francis Conley','F','uneven parallel bars','Individual','Hannah Amber','MY','NULL',37,14),
(437,'Zander Ivy','F','vaulting','Individual','Wyatt Aquamarine','MY','NULL',38,28),
(438,'Kaiden Snead','F','handball','Individual','Layla Pearl','MY','NULL',39,19),
(439,'Elena Frantz','F','horseshoe pitching','Individual','Sebastian Steel','MY','NULL',40,35),
(440,'Irene Spain','F','jai alai','Individual','Zoe Bronze','MY','NULL',41,31),
(441,'Sherman Lindley','F','martial arts','Individual','Gavin Black','MY','NULL',42,29),
(442,'Latavia Harris','F','aikido','Individual','Chloe White','MY','NULL',43,31),
(443,'Briar McCormick','F','capoeira','Individual','Elijah Indigo','MY','NULL',44,19),
(444,'Kallie Merrick','F','hapkido','Individual','Grace Golden','MY','NULL',45,28),
(445,'Valencia Royer','F','judo','Individual','Carter Violet','MY','NULL',46,14),
(446,'Alden Olson','F','jujitsu','Individual','Addison Burgundy','MY','NULL',47,27),
(447,'Osvaldo Mackay','F','karate','Individual','Landon Chartreuse','MY','NULL',48,35),
(448,'Alana Kerr','F','kendō','Individual','Lucy Salmon','MY','NULL',49,30),
(449,'Devon Grubb','F','kung fu','Individual','Lincoln Olive','AUS','NULL',50,21),
(450,'Easton Brantley','F','pankration','Individual','Natalie Chocolate','AUS','NULL',51,35),
(451,'Braiden McCarthy','F','savate','Individual','Austin Cyan','AUS','NULL',52,20),
(452,'Sierra Boyd','F','tai chi chuan','Individual','Ellie Gray','AUS','NULL',53,21),
(453,'Alanna Whitman','F','tae kwon do','Individual','Brayden Purple','AUS','NULL',54,14),
(454,'Frankie Maher','F','mountaineering','Individual','Nora Tangerine','AUS','NULL',55,32),
(455,'Shae Matthews','F','orienteering','Individual','Gabriel Coral','AUS','NULL',56,21),
(456,'Trayvon Cohen','F','pall-mall','Individual','Madison Mint','AUS','NULL',57,26),
(457,'Makenzie Segura','F','pelota','Individual','Hunter Magenta','AUS','NULL',58,31),
(458,'Zackery Albertson','M','pentathlon','Individual','Samantha Lime','AUS','NULL',59,26),
(459,'Stanley Laws','M','quoits','Individual','Colton Teal','AUS','NULL',60,28),
(460,'Lea Joyce','M','rackets','Individual','Peyton Gold','AUS','NULL',61,28),
(461,'Taylor Luce','M','racquetball','Individual','Nicholas Pink','AUS','NULL',62,22),
(462,'Geovanni Roy','M','real tennis','Individual','Alyssa Beige','AUS','NULL',63,27),
(463,'Shaniya Lemay','M','shooting','Individual','Dylan Orange','AUS','NULL',64,31),
(464,'Tavion Doe','M','skeet shooting','Individual','Mila Blue','AUS','NULL',65,26),
(465,'Madalynn Bunting','M','trapshooting','Individual','Zachary Coral','AUS','NULL',66,21),
(466,'Kevin Vega','M','shuffleboard','Individual','Cora Indigo','AUS','NULL',67,29),
(467,'Jaidyn Fitzgerald','M','skating','Individual','Nathan Purple','AUS','NULL',68,26),
(468,'Riley Sturgeon','M','ice skating','Individual','Victoria Gray','AUS','NULL',69,30),
(469,'Milo Chastain','M','figure skating','Individual','Harrison Tan','AUS','NULL',70,22),
(470,'Makaela Lea','M','speed skating','Individual','Madeline Raspberry','AUS','NULL',71,22),
(471,'America North','M','short-track speed skating','Individual','Ian Salmon','AUS','NULL',72,17),
(472,'Lexi Cornell','M','roller-skating','Individual','Penelope White','AUS','NULL',73,24),
(473,'Chandler Mortensen','M','skibobbing','Individual','Dominic Magenta','AUS','NULL',74,18),
(474,'Amiyah Molina','M','skiing','Individual','Aurora Lavender','AUS','NULL',75,31),
(475,'Nathen Hickey','M','Alpine skiing','Individual','Julian Beige','AUS','NULL',76,34),
(476,'Angeline Dowdy','M','downhill skiing','Individual','Bella Cyan','AUS','NULL',77,16),
(477,'Jennah Robinette','M','slalom','Individual','Thomas Coral','AUS','NULL',78,28),
(478,'Travis Stafford','M','freestyle skiing','Individual','Natalia Plum','AUS','NULL',79,32),
(479,'Aaron Galvan','M','Nordic skiing','Individual','Leo Gray','AUS','NULL',80,17),
(480,'Stephen Seibert','M','cross-country skiing','Individual','Lila Gold','AUS','NULL',81,15),
(481,'Blair Edmonds','M','ski jumping','Individual','Xavier Brown','AUS','NULL',82,35),
(482,'Adrienne Oshea','M','speed skiing','Individual','Riley Pink','AUS','NULL',83,34),
(483,'Imani Grimes','M','waterskiing','Individual','Brandon Orange','AUS','NULL',84,18),
(484,'Kamron Tavares','M','snowboarding','Individual','Addison Lime','AUS','NULL',85,33),
(485,'Lizeth Lively','M','squash rackets','Individual','Aiden Teal','AUS','NULL',86,29),
(486,'Ariel Rector','M','squash tennis','Individual','Claire Violet','USA','NULL',87,25),
(487,'Kegan Posey','M','swimming','Individual','Logan Indigo','USA','NULL',88,34),
(488,'Emilie Yu','M','synchronized swimming','Individual','Eva Coral','USA','NULL',89,32),
(489,'Carter Rudolph','M','tennis','Individual','Isaiah Purple','USA','NULL',90,26),
(490,'Jessalyn Gresham','M','paddle tennis','Individual','Daphne Tan','USA','NULL',91,15),
(491,'Dejon Johansen','M','table tennis','Individual','Jason Blue','USA','NULL',92,34),
(492,'Gabriel Forte','M','track-and-field sports/athletics','Individual','Sophie Mint','USA','NULL',93,33),
(493,'Cailin Farley','M','decathlon','Individual','Caleb Gray','USA','NULL',94,15),
(494,'Elyssa Peoples','M','discus throw','Individual','Lily Burgundy','USA','NULL',95,29),
(495,'Denver Venable','M','hammer throw','Individual','Tyler Olive','USA','NULL',96,33),
(496,'Sky Beyer','M','heptathlon','Individual','Julia Golden','USA','NULL',97,33),
(497,'Latavia Chamberlin','M','high jump','Individual','Adrian Black','USA','NULL',98,19),
(498,'Raegan Hammer','M','javelin throw','Individual','Nina Lavender','USA','NULL',99,30),
(499,'Dallin Gay','M','long jump','Individual','Gavin Coral','USA','NULL',100,32),
(500,'Javonte Boss','M','pole vault','Individual','Yamileth Mena','USA','NULL',101,20),
(501,'Demarcus Cote','M','running','Individual','Jaylen Connelly','USA','NULL',102,25),
(502,'Nathaly Bohannon','M','hurdling','Individual','Aaliyah Coronado','USA','NULL',103,30),
(503,'Clarence Swift','M','long-distance running','Individual','Sequoia Stanley','USA','NULL',104,14),
(504,'Aleena Harrison','M','marathon','Individual','Ramiro Slocum','USA','NULL',105,34),
(505,'Dakota Noriega','M','middle-distance running','Individual','Valeria Cullen','USA','NULL',106,19),
(506,'Itzel Story','M','sprint','Individual','Kami Richey','USA','NULL',107,23),
(507,'Nelson Wang','M','steeplechase','Individual','Cherokee Whitley','USA','NULL',108,30),
(508,'Star Nash','M','shot put','Individual','Yosef Cline','USA','NULL',109,18),
(509,'Jaida Womack','M','triple jump','Individual','Charlie Andersen','USA','NULL',110,17),
(510,'Vincenzo Rowan','M','triathlon','Individual','Gunner Lott','USA','NULL',111,18),
(511,'Hali Chao','M','underwater diving','Individual','Chyanne Vergara','USA','NULL',112,18),
(512,'Amina Coon','M','weightlifting','Individual','Brennen Sample','USA','NULL',113,14),
(513,'Kelsi McGrath','M','powerlifting','Individual','Harold Helton','USA','NULL',114,16),
(514,'Mason MacDonald','M','weight throw','Individual','Carley Stock','USA','NULL',115,28),
(515,'Tamara Kunkel','M','wrestling','Individual','Jorge Heim','USA','NULL',116,28),
(516,'Emilia Dix','M','catch-as-catch-can wrestling','Individual','Nelly Hillman','USA','NULL',117,34),
(517,'Tristin Rodrigues','M','Cornish wrestling','Individual','Russell Paredes','USA','NULL',118,16),
(518,'Marion Samuels','M','Cumberland wrestling','Individual','Dalila Neely','USA','NULL',119,22),
(519,'Warren Chaney','M','freestyle wrestling','Individual','Damon Pearson','USA','NULL',120,21),
(520,'Drew Peterson','M','Greco-Roman wrestling','Individual','Caley Aviles','USA','NULL',121,32),
(521,'Stevie Croft','M','sambo','Individual','Treyton Ott','USA','NULL',122,34),
(522,'Rodolfo Colwell','M','Schwingen','Individual','Paxton Eddy','USA','NULL',123,28),
(523,'Julisa Zielinski','M','sumo','Individual','Erica Villarreal','USA','NULL',124,15),
(524,'Alisa Dent','M','archery','Individual','London Colon','USA','NULL',125,27),
(525,'Jaycob Newton','M','association croquet','Team','Darwin Julian','USA','TeamMY',126,32),
(526,'George Hager','M','badminton','Team','Shira Zeigler','USA','TeamMY',127,17),
(527,'Amina Sterling','M','bandy','Team','Jayden Madrid','USA','TeamMY',128,19),
(528,'Renae Crook','M','baseball','Team','Lillie Lim','USA','TeamMY',129,34),
(529,'Aislinn Poston','M','basketball','Team','Deangelo Dell','USA','TeamMY',130,31),
(530,'Baylor Haskins','M','biathlon','Team','Tyrek Workman','USA','TeamMY',131,22),
(531,'Reagan Bowers','M','boccie','Team','Whitney Haas','USA','TeamMY',132,29),
(532,'Cheyenne Crow','F','boules','Team','Joselin Forte','USA','TeamMY',133,24),
(533,'Adrian Paredes','F','bowling','Team','Yolanda Moulton','USA','TeamMY',134,32),
(534,'Bailee Moffitt','F','candlepins','Team','Tristan Maas','USA','TeamMY',135,14),
(535,'Sawyer Oreilly','F','cocked hat','Team','Ryley Perez','USA','TeamMY',136,24),
(536,'Elliot Arellano','F','duckpins','Team','Jennifer Waller','USA','TeamMY',137,29),
(537,'Katia Woodruff','F','bowls','Team','Dakota Luciano','USA','TeamMY',138,15),
(538,'Heidy Gagnon','F','cricket','Team','Connor Forman','USA','TeamMY',139,29),
(539,'Christie Kahn','F','Twenty20 cricket','Team','Jamie Grice','USA','TeamMY',140,15),
(540,'Keandre Martel','F','croquet','Team','Alejandro Han','USA','TeamMY',141,31),
(541,'Neo Banda','F','cross-country','Team','Sunny Crabtree','USA','TeamMY',142,22),
(542,'Sherman Pace','F','curling','Team','Cayden Kirk','USA','TeamMY',143,18),
(543,'Tionna Ponce','F','darts','Team','Adonis Bassett','USA','TeamMY',144,21),
(544,'Adolfo Bello','F','deck tennis','Team','Keaton Murry','USA','TeamMY',145,30),
(545,'Sabastian Poole','F','Eisstockschiessen','Team','Kiera Fisk','USA','TeamMY',146,31),
(546,'Devon Preston','F','field hockey','Team','Blaise Muir','USA','TeamMY',147,20),
(547,'Alani Lau','F','fives','Team','Kalen Riggs','USA','TeamMY',148,21),
(548,'Ivana Bunch','F','football','Team','Saul Masterson','USA','TeamMY',149,14),
(549,'Zoie Powers','F','Australian rules football','Team','John Powell','USA','TeamMY',150,15),
(550,'Stefan Mullen','F','football soccer','Team','Lizet Emerson','USA','TeamMY',151,20),
(551,'Martina Marks','F','Gaelic football','Team','Domenic Rucker','USA','TeamMY',152,28),
(552,'Shaina Dodge','F','gridiron football','Team','Joslyn Lunsford','USA','TeamMY',153,27),
(553,'Maggie Quiroz','F','rugby','Team','Shekinah Gilchrist','USA','TeamMY',154,18),
(554,'Alina Easley','F','gymnastics','Team','Kallie Delacruz','USA','TeamMY',155,19),
(555,'River Andrade','F','rhythmic gymnastics','Team','Casey Havens','USA','TeamMY',156,19),
(556,'Lucia Snyder','F','handball','Team','Alexandre Rao','USA','TeamMY',157,35),
(557,'Aubree Garber','F','Hooverball','Team','Bridgett Alvarez','USA','TeamMY',158,14),
(558,'Austyn Chen','F','horseshoe pitching','Team','Danae Morrison','USA','TeamMY',159,17),
(559,'Raegan Strain','F','hurling','Team','Jeanette Robison','USA','TeamMY',160,15),
(560,'Annalise Mejia','F','ice hockey','Team','Kelsea Hein','USA','TeamMY',161,26),
(561,'Frankie Meador','F','jai alai','Team','Demetria Villalobos','USA','TeamMY',162,24),
(562,'Evelyn Alonzo','F','kabaddi','Team','Sean Spivey','USA','TeamMY',163,33),
(563,'Rico Brittain','F','korfball','Team','Trae Delgadillo','USA','TeamMY',164,18),
(564,'Lionel Taggart','F','lacrosse','Team','Tomas Horowitz','USA','TeamMY',165,21),
(565,'Tayler Temple','F','box lacrosse','Team','Byron Vazquez','USA','TeamMY',166,19),
(566,'Akira Apodaca','F','netball','Team','Brennon Levesque','USA','TeamMY',167,15),
(567,'Aliza Haney','F','orienteering','Team','Corrine Haase','USA','TeamMY',168,16),
(568,'Michele Goodson','F','pelota','Team','Matteo Donovan','UK','TeamMY',169,35),
(569,'Raven Fortin','F','rackets','Team','Robert Weiss','UK','TeamMY',170,20),
(570,'Micheal Newell','F','racquetball','Team','Callie McClellan','UK','TeamMY',171,35),
(571,'Yulisa Ainsworth','F','real tennis','Team','Giselle Rincon','UK','TeamMY',172,30),
(572,'Haleigh Blanco','F','rounders','Team','Elliott Sanders','UK','TeamMY',173,25),
(573,'Coby Powers','F','skating','Team','Xochitl Clapp','UK','TeamMY',174,14),
(574,'Perry McDonnell','F','figure skating','Team','Marlon Briones','UK','TeamAUS',175,22),
(575,'Paloma Connor','F','roller-skating','Team','Derek Shepherd','UK','TeamAUS',176,29),
(576,'Ken Isbell','F','speed skating','Team','Tyrek Frost','UK','TeamAUS',177,19),
(577,'Matteo Steen','F','skiing','Team','Jamar Byrne','UK','TeamAUS',178,15),
(578,'Tyrek Holtz','F','Nordic skiing','Team','Ronald Meza','UK','TeamAUS',179,22),
(579,'Lynsey Marin','F','cross-country skiing','Team','Stone Hays','UK','TeamAUS',180,24),
(580,'Carrie Sheffield','F','shinty','Team','Joaquin Falcon','UK','TeamAUS',181,15),
(581,'Rachel Gooch','F','shuffleboard','Team','Jaylen Crocker','UK','TeamAUS',182,30),
(582,'Keila Gulley','F','softball','Team','Mika Hanlon','UK','TeamAUS',183,26),
(583,'Abram Petty','F','squash rackets','Team','Destiney Calderon','UK','TeamAUS',184,22),
(584,'Grecia Smalley','F','swimming','Team','Shelton Nadeau','UK','TeamAUS',185,26),
(585,'Kristy Freeman','F','synchronized swimming','Team','Monika McManus','UK','TeamAUS',186,34),
(586,'Pedro Jensen','F','table tennis','Team','Mikael Machado','UK','TeamAUS',187,24),
(587,'Michele Early','F','team handball','Team','Gracie Neely','UK','TeamAUS',188,33),
(588,'Audra Wesley','F','tennis','Team','Aimee Clifton','UK','TeamAUS',189,28),
(589,'Erik Russ','F','paddle tennis','Team','Jimmie Haggerty','UK','TeamAUS',190,14),
(590,'Diane Garcia','F','table tennis','Team','Ray Neal','UK','TeamAUS',191,23),
(591,'Joseluis Greenberg','F','track-and-field sports/athletics','Team','Jaiden Watson','UK','TeamAUS',192,31),
(592,'Kirk Bartholomew','F','running','Team','Carlee Nance','UK','TeamAUS',193,21),
(593,'Mackenzi Upton','F','relay race','Team','Will Heaton','UK','TeamAUS',194,35),
(594,'Logan Aiken','F','triathlon','Team','Leandra Conner','UK','TeamAUS',195,31),
(595,'Jaren McClain','F','tug-of-war','Team','Andie Jansen','UK','TeamAUS',196,22),
(596,'Kyron Jacob','F','volleyball','Team','Shea Lea','UK','TeamAUS',197,29),
(597,'Juana Fusco','F','water polo','Team','Nestor Sewell','UK','TeamAUS',198,17),
(598,'Kegan High','F','Diving','Team','Luc Gross','UK','TeamAUS',199,15),
(599,'Elian Nash','F','basketball','Team','Cristobal Mathis','UK','TeamAUS',200,21),
(600,'Hezekiah Dorsey','F','aerobatics','Team','Beverly Parnell','UK','TeamAUS',201,20),
(601,'Tracy Knudsen','F','air racing','Team','Paige Herzog','UK','TeamAUS',202,34),
(602,'Garrett Apodaca','F','automobile racing','Team','Bradley Mello','UK','TeamAUS',203,19),
(603,'Devlin Fair','F','drag racing','Team','Victoria Sawyer','UK','TeamAUS',204,23),
(604,'Antonia Hansen','F','Grand Prix racing','Team','Ananda Mathew','UK','TeamAUS',205,14),
(605,'Alfred Francois','F','gymkhana','Team','Lyndsay Bello','UK','TeamAUS',206,26),
(606,'Jonathan Mackey','F','hill climb','Team','Edward Gillette','UK','TeamAUS',207,14),
(607,'Babygirl Banuelos','F','karting','Team','Isabella Popp','UK','TeamAUS',208,20),
(608,'Nikole Malley','F','midget-car racing','Team','Yasmine Prather','UK','TeamAUS',209,16),
(609,'Alea Peebles','F','offroad racing','Team','Emily Lea','UK','TeamAUS',210,32),
(610,'Paris Falk','F','rally','Team','Stacie Albert','UK','TeamAUS',211,34),
(611,'Giancarlo Capps','F','speedway racing','Team','Mariela Eller','UK','TeamUSA',212,18),
(612,'Seamus Culp','F','sports-car racing','Team','Immanuel Johnson','UK','TeamUSA',213,31),
(613,'Kellen Collazo','F','stock-car racing','Team','Katy Carl','UK','TeamUSA',214,16),
(614,'Layla Neely','F','ballooning','Team','Kade Swafford','UK','TeamUSA',215,14),
(615,'Gene Chambers','F','bullfighting','Team','Garrett Pool','UK','TeamUSA',216,28),
(616,'Tai Mott','F','rejoneo','Team','Daijah Messer','UK','TeamUSA',217,15),
(617,'Destin Zeller','F','bungee jumping','Team','Alysa Donnelly','UK','TeamUSA',218,33),
(618,'Christen Furman','F','camel racing','Team','Yasmeen Dow','UK','TeamUSA',219,35),
(619,'Kareem Turpin','F','canoeing','Team','Janna Marin','UK','TeamUSA',220,16),
(620,'Brenton Shelby','F','wild-water racing','Team','Rita Villasenor','UK','TeamUSA',221,15),
(621,'Brannon Andres','F','cockfighting','Team','Dale Connor','NZ','TeamUSA',222,30),
(622,'Charlize Childs','F','cycling','Team','Tylor Sikes','NZ','TeamUSA',223,19),
(623,'Blair Betz','F','cycle ball','Team','Jill Custer','NZ','TeamUSA',224,29),
(624,'Brenden Gamez','F','cyclo-cross','Team','Emanuel Castellanos','NZ','TeamUSA',225,16),
(625,'Stevie Bohannon','F','motor-paced race','Team','Brian Ray','NZ','TeamUSA',226,16),
(626,'Shivani Gunn','F','pursuit racing','Team','Xavier Merriman','NZ','TeamUSA',227,22),
(627,'Alyssa Lockett','F','road race','Team','Leonel Bowser','NZ','TeamUSA',228,17),
(628,'Magali Uribe','M','pursuit racing','Team','Waylon Gibson','NZ','TeamUSA',229,18),
(629,'Franklin Gallo','M','road race','Team','Wilson Parris','NZ','TeamUSA',230,33),
(630,'Lea Bustamante','M','six-day race','Team','Kameron Liang','NZ','TeamUSA',231,27),
(631,'Juliana Finnegan','M','sprint','Team','Ashton Reyna','NZ','TeamUSA',232,33),
(632,'Aylin Crabtree','M','dog racing','Team','Charity Tompkins','NZ','TeamUSA',233,28),
(633,'Serena Love','M','dogsled racing','Team','Guadalupe Wilcox','NZ','TeamUSA',234,19),
(634,'Anton Cerda','M','fishing','Team','Melia Lawson','NZ','TeamUSA',235,18),
(635,'Gabrielle Schwartz','M','fly-fishing','Team','Vicky Wellman','NZ','TeamUSA',236,28),
(636,'Vera Champagne','M','gladiatorial sports','Team','Nayely Barton','NZ','TeamUSA',237,32),
(637,'Alyssa Palermo','M','venationes','Team','Candy Headley','NZ','TeamUSA',238,26),
(638,'Allyssa Kearney','M','gliding','Team','Larissa Pruett','NZ','TeamUSA',239,33),
(639,'Jimmy Power','M','hang gliding','Team','Sasha Marino','NZ','TeamUSA',240,28),
(640,'Shane Shay','M','paragliding','Team','Earl Coughlin','NZ','TeamUSA',241,34),
(641,'Breann Rios','M','horsemanship','Team','Sheyla Monroy','NZ','TeamUSA',242,29),
(642,'Ivanna Bliss','M','buzkashī','Team','Emma Patton','CND','TeamUSA',243,14),
(643,'Anisa Duran','M','chariot racing','Team','Donnie Timmons','CND','TeamUSA',244,15),
(644,'Toby Partridge','M','dressage','Team','Parker Smart','CND','TeamUSA',245,23),
(645,'Wyatt Chastain','M','harness racing','Team','Valerie Whittington','CND','TeamUSA',246,35),
(646,'Ean Goss','M','horse racing','Team','Phoenix Edmonds','CND','TeamUSA',247,20),
(647,'Anders Owens','M','hurdle race','Team','Avery Redden','CND','TeamUSA',248,26),
(648,'Maverick Hu','M','joust','Team','Jadyn Baum','CND','TeamUSA',249,24),
(649,'Kinsey Hernandez','M','point-to-point','Team','Benjamin Galbraith','CND','TeamUSA',250,32),
(650,'Ricky Cummings','M','quarter-horse racing','Team','Lamont Hamlin','CND','TeamUSA',251,19),
(651,'Kayden Corcoran','M','show jumping','Team','Stephany Redmond','CND','TeamUSA',252,18),
(652,'Malcolm Holly','M','steeplechase','Team','Esther Kang','CND','TeamUSA',253,17),
(653,'Enoch Hook','M','hunting','Team','Heidy Bock','CND','TeamUSA',254,16),
(654,'Nolan Cheng','M','coursing','Team','Kobi Araujo','CND','TeamUSA',255,25),
(655,'Ezekiel Oakes','M','falconry','Team','Cullen Gilmore','CND','TeamUSA',256,35),
(656,'Malorie Carmichael','M','field trial','Team','Kelsey Autry','CND','TeamUSA',257,26),
(657,'Cooper Dutton','M','foxhunting','Team','Sam Cordell','CND','TeamUSA',258,19),
(658,'Austin Ventura','M','iceboating','Team','Rodney Johns','CND','TeamUSA',259,14),
(659,'Kiara Hobbs','M','motorcycle racing','Team','Morris Rao','CND','TeamUSA',260,24),
(660,'Laisha Withrow','M','motocross','Team','Leanne Kelsey','CND','TeamUSA',261,17),
(661,'Danica Aquino','M','motorcycle trial','Team','Jefferson Kunz','CND','TeamUSA',262,19),
(662,'Kylah Lackey','M','motor-paced race','Team','Lizette Wilbur','CND','TeamUSA',263,21),
(663,'Rocky Joy','M','offroad racing','Team','Carly Helm','CND','TeamUSA',264,22),
(664,'Zane Cerda','M','speedway racing','Team','Kristen Brinkman','CND','TeamUSA',265,16),
(665,'Nathanael Case','M','pigeon racing','Team','Cody Gore','CND','TeamUSA',266,24),
(666,'Ayana Rhoads','M','polo','Team','Tyron Benedict','CND','TeamUSA',267,35),
(667,'Damaris Masterson','M','polocrosse','Team','Galen Joe','CND','TeamUSA',268,35),
(668,'Hayli Lombardi','M','rodeo','Team','Angeles Hennessy','CND','TeamUSA',269,18),
(669,'Annalisa Bunting','M','bareback bronc-riding','Team','Aliza Fugate','CND','TeamUSA',270,28),
(670,'Monique Holliday','M','bull riding','Team','Antoinette Underwood','CND','TeamUSA',271,28),
(671,'Bryson Ketchum','M','calf roping','Team','Kyndall Hudson','CND','TeamUSA',272,14),
(672,'Moises Merchant','M','steer roping','Team','Randall Beal','CHN','TeamUSA',273,35),
(673,'Carter Falcon','M','steer wrestling','Team','Saira Wirth','CHN','TeamUSA',274,26),
(674,'Ryan Geary','M','team roping','Team','Coleton Raines','CHN','TeamUSA',275,34),
(675,'Kurtis Kohler','M','rowing','Team','Chaim Hillman','CHN','TeamUSA',276,33),
(676,'Adonis Keane','M','skateboarding','Team','Jayden Dyson','CHN','TeamUSA',277,29),
(677,'Kaci Merrick','M','skydiving','Team','Irma Goforth','CHN','TeamUSA',278,14),
(678,'Kaycee Flannery','M','sledding','Team','Daysha Hamlin','CHN','TeamUSA',279,30),
(679,'Chyna Steinberg','M','bobsledding','Team','Sidney Hanley','CHN','TeamUSA',280,24),
(680,'Pedro Joiner','M','lugeing','Team','Sergio Castle','CHN','TeamUSA',281,31),
(681,'Anastacia Pelletier','M','skeleton sledding','Team','Zechariah Everhart','CHN','TeamUSA',282,20),
(682,'Daija Snowden','M','tobogganing','Team','Nathen Hawks','CHN','TeamUSA',283,26),
(683,'Zachary Sweat','M','surfing','Team','Shelby Larue','CHN','TeamUSA',284,23),
(684,'London Hein','M','windsurfing','Team','Celina Darnell','CHN','TeamUSA',285,16),
(685,'Kennedy Carlton','M','tournament','Team','Dorian Nance','CHN','TeamUSA',286,29),
(686,'Nichole Aleman','M','mêlée','Team','Mohammad McGowan','CHN','TeamUSA',287,14),
(687,'Damaris Dawson','M','Badminton','Team','Theo Villareal','CHN','TeamUSA',288,25),
(688,'Ciana Rowley','M','Baseball 5','Team','Treyton Ely','CHN','TeamUSA',289,16),
(689,'Tristin French','M','Baseball Softball','Team','Tania Hendrix','CHN','TeamUSA',290,18),
(690,'Hazel Barnes','M','Basketball','Team','Madilyn Danner','CHN','TeamUSA',291,22),
(691,'Tomas Larkin','M','Basketball 3x3','Team','Casandra Paquette','CHN','TeamUSA',292,24),
(692,'Ricky Faber','M','Beach Handball','Team','Peyton Bohannon','SG','TeamUSA',293,34),
(693,'Rodrigo Begley','M','Beach Volleyball','Team','Louie Cable','SG','TeamUK',294,17),
(694,'Tyshawn Kim','M','Biathlon','Team','Mya Tubbs','SG','TeamUK',295,24),
(695,'Deshawn Marino','M','Bobsleigh','Team','Alivia Ridenour','SG','TeamUK',296,23),
(696,'Tionne Fulton','M','Boxing','Team','Jazlynn Monson','SG','TeamUK',297,29),
(697,'Ajay Mcgrew','M','Breaking','Team','Oliver Tomlinson','SG','TeamUK',298,24),
(698,'Sasha Barajas','M','swimming','Team','Kristi Walden','SG','TeamUK',299,16),
(699,'Ralph Redd','M','Badminton','Team','Noemi Henson','SG','TeamUK',300,19),
(700,'Jillian Moyer','F','clout shooting','Individual','John Doe','MY','NULL',1,30),
(701,'Jakob Perrin','F','field archery','Individual','Jane Smith','MY','NULL',2,23),
(702,'Kacey Mueller','F','flight shooting','Individual','Mike Brown','MY','NULL',3,14),
(703,'Solomon Nava','F','kyūdō','Individual','Emily White','MY','NULL',4,19),
(704,'Kadin Sexton','F','roving','Individual','Chris Green','MY','NULL',5,26),
(705,'Rubi Gleason','F','association croquet','Individual','Sarah Black','MY','NULL',6,25),
(706,'Shanice Sloan','F','badminton','Individual','James Blue','MY','NULL',7,30),
(707,'Lamar Arteaga','F','biathlon','Individual','Anna Grey','MY','NULL',8,33),
(708,'Makaylah Hearn','F','birling','Individual','David Red','MY','NULL',9,14),
(709,'Halle Mares','F','boccie','Individual','Olivia Pink','MY','NULL',10,16),
(710,'Fidel Hankins','F','bodybuilding','Individual','Daniel Yellow','MY','NULL',11,32),
(711,'Rachael Funk','F','boules','Individual','Mia Purple','MY','NULL',12,15),
(712,'Kobe Allan','F','bowling','Individual','Liam Orange','MY','NULL',13,19),
(713,'Dominic Ybarra','F','candlepins','Individual','Ava Brown','MY','NULL',14,34),
(714,'Tanner Leger','F','cocked hat','Individual','Noah Silver','MY','NULL',15,30),
(715,'Kristina High','F','duckpins','Individual','Sophia Gold','MY','NULL',16,34),
(716,'Leslie Heinz','F','ninepins','Individual','Lucas Teal','MY','NULL',17,25),
(717,'Jacqueline Betancourt','F','skittles','Individual','Isabella Coral','MY','NULL',18,35),
(718,'Macie Briscoe','F','bowls','Individual','Ethan Indigo','MY','NULL',19,33),
(719,'Dante Ceballos','F','boxing','Individual','Charlotte Lime','MY','NULL',20,25),
(720,'Marianna Rafferty','F','croquet','Individual','Jackson Olive','MY','NULL',21,32),
(721,'Terrence Espino','F','cross-country','Individual','Amelia Mint','MY','NULL',22,19),
(722,'Chelsea Pearson','F','darts','Individual','Aiden Cherry','MY','NULL',23,31),
(723,'Abigayle Doty','F','deck tennis','Individual','Harper Plum','MY','NULL',24,28),
(724,'Terrance Knudsen','F','diving','Individual','Samuel Maroon','MY','NULL',25,17),
(725,'Ignacio McCurdy','M','fencing','Individual','Mason Beige','MY','NULL',26,29),
(726,'Yvette High','M','kendo','Individual','Ella Cyan','MY','NULL',27,25),
(727,'Mohammed Bradshaw','M','golf','Individual','Henry Magenta','MY','NULL',28,18),
(728,'Beatrice Streeter','M','gymnastics','Individual','Victoria Peach','MY','NULL',29,22),
(729,'Adrian Bess','M','balance beam','Individual','Logan Tan','MY','NULL',30,24),
(730,'Viviana Hauser','M','floor exercise','Individual','Aria Gray','MY','NULL',31,31),
(731,'Silas Mahan','M','horizontal bar','Individual','Owen Salmon','MY','NULL',32,18),
(732,'Natalee Lewis','M','parallel bars','Individual','Scarlett Lavender','MY','NULL',33,22),
(733,'Sterling Calderon','M','pommel horse','Individual','Maverick Raspberry','MY','NULL',34,19),
(734,'Carolina Talbot','M','rhythmic gymnastics','Individual','Ella Rose','MY','NULL',35,31),
(735,'Dwight Cummins','M','rings','Individual','Daniel Mint','MY','NULL',36,32),
(736,'Rowan Reinhart','M','uneven parallel bars','Individual','Hannah Amber','MY','NULL',37,22),
(737,'Danika Michaud','M','vaulting','Individual','Wyatt Aquamarine','MY','NULL',38,31),
(738,'Sterling Adams','M','handball','Individual','Layla Pearl','MY','NULL',39,35),
(739,'Deana Girard','M','horseshoe pitching','Individual','Sebastian Steel','MY','NULL',40,26),
(740,'Galen Swisher','M','jai alai','Individual','Zoe Bronze','MY','NULL',41,21),
(741,'Jeffery Wilks','M','martial arts','Individual','Gavin Black','MY','NULL',42,34),
(742,'Wilson Artis','M','aikido','Individual','Chloe White','MY','NULL',43,17),
(743,'Jensen McNeal','M','capoeira','Individual','Elijah Indigo','MY','NULL',44,14),
(744,'Jamaal Kitchens','M','hapkido','Individual','Grace Golden','MY','NULL',45,14),
(745,'Eryn Avila','M','judo','Individual','Carter Violet','MY','NULL',46,20),
(746,'Tavon Dickerson','M','jujitsu','Individual','Addison Burgundy','MY','NULL',47,22),
(747,'Deon Fitzpatrick','M','karate','Individual','Landon Chartreuse','MY','NULL',48,27),
(748,'Dalia Huber','M','kendō','Individual','Lucy Salmon','MY','NULL',49,35),
(749,'Alejandro Muller','M','kung fu','Individual','Lincoln Olive','AUS','NULL',50,17),
(750,'Veronica Samuel','M','pankration','Individual','Natalie Chocolate','AUS','NULL',51,26),
(751,'Gianna Sells','M','savate','Individual','Austin Cyan','AUS','NULL',52,18),
(752,'Stephon Bonds','M','tai chi chuan','Individual','Ellie Gray','AUS','NULL',53,33),
(753,'Triniti Chavez','M','tae kwon do','Individual','Brayden Purple','AUS','NULL',54,29),
(754,'Ian Dupont','M','mountaineering','Individual','Nora Tangerine','AUS','NULL',55,14),
(755,'Pilar Mckinley','M','orienteering','Individual','Gabriel Coral','AUS','NULL',56,21),
(756,'Darrian Perry','M','pall-mall','Individual','Madison Mint','AUS','NULL',57,33),
(757,'Ernest Spangler','M','pelota','Individual','Hunter Magenta','AUS','NULL',58,21),
(758,'Adeline Bruner','M','pentathlon','Individual','Samantha Lime','AUS','NULL',59,29),
(759,'Tobias McGregor','M','quoits','Individual','Colton Teal','AUS','NULL',60,23),
(760,'Brooklynn Hillman','M','rackets','Individual','Peyton Gold','AUS','NULL',61,21),
(761,'Duncan Judge','M','racquetball','Individual','Nicholas Pink','AUS','NULL',62,25),
(762,'Haley Valdes','M','real tennis','Individual','Alyssa Beige','AUS','NULL',63,27),
(763,'Tamara Vigil','M','shooting','Individual','Dylan Orange','AUS','NULL',64,18),
(764,'Deante Moran','M','skeet shooting','Individual','Mila Blue','AUS','NULL',65,24),
(765,'Raelynn Huey','M','trapshooting','Individual','Zachary Coral','AUS','NULL',66,21),
(766,'Jericho Alcantar','M','shuffleboard','Individual','Cora Indigo','AUS','NULL',67,33),
(767,'Kirstyn Carlos','M','skating','Individual','Nathan Purple','AUS','NULL',68,14),
(768,'Shiann Slone','M','ice skating','Individual','Victoria Gray','AUS','NULL',69,15),
(769,'Maricela Atkinson','M','figure skating','Individual','Harrison Tan','AUS','NULL',70,18),
(770,'Brittani Hinton','M','speed skating','Individual','Madeline Raspberry','AUS','NULL',71,29),
(771,'Gavyn Seaman','M','short-track speed skating','Individual','Ian Salmon','AUS','NULL',72,16),
(772,'Shelbie Carl','M','roller-skating','Individual','Penelope White','AUS','NULL',73,29),
(773,'Kyndall Marshall','M','skibobbing','Individual','Dominic Magenta','AUS','NULL',74,26),
(774,'Clara Poole','M','skiing','Individual','Aurora Lavender','AUS','NULL',75,30),
(775,'Sydnee Lane','M','Alpine skiing','Individual','Julian Beige','AUS','NULL',76,32),
(776,'Menachem Deaton','M','downhill skiing','Individual','Bella Cyan','AUS','NULL',77,19),
(777,'Eleanor Lynch','M','slalom','Individual','Thomas Coral','AUS','NULL',78,14),
(778,'Derrick Chavis','M','freestyle skiing','Individual','Natalia Plum','AUS','NULL',79,14),
(779,'Deja Moore','M','Nordic skiing','Individual','Leo Gray','AUS','NULL',80,22),
(780,'Scott Kiser','M','cross-country skiing','Individual','Lila Gold','AUS','NULL',81,19),
(781,'Pearl Kasper','M','ski jumping','Individual','Xavier Brown','AUS','NULL',82,14),
(782,'Tyson Leon','M','speed skiing','Individual','Riley Pink','AUS','NULL',83,29),
(783,'Marlene Poirier','M','waterskiing','Individual','Brandon Orange','AUS','NULL',84,29),
(784,'Bridget Marquis','M','snowboarding','Individual','Addison Lime','AUS','NULL',85,23),
(785,'Moshe Marquardt','M','squash rackets','Individual','Aiden Teal','AUS','NULL',86,34),
(786,'Eddy Maddox','M','squash tennis','Individual','Claire Violet','USA','NULL',87,25),
(787,'Alfred Platt','M','swimming','Individual','Logan Indigo','USA','NULL',88,16),
(788,'Lawrence Hilton','M','synchronized swimming','Individual','Eva Coral','USA','NULL',89,15),
(789,'Moshe Hackney','M','tennis','Individual','Isaiah Purple','USA','NULL',90,22),
(790,'Kimberley Mattox','M','paddle tennis','Individual','Daphne Tan','USA','NULL',91,14),
(791,'Santana Bradshaw','M','table tennis','Individual','Jason Blue','USA','NULL',92,18),
(792,'Broderick Martz','M','track-and-field sports/athletics','Individual','Sophie Mint','USA','NULL',93,25),
(793,'Regina Galvez','M','decathlon','Individual','Caleb Gray','USA','NULL',94,20),
(794,'Kelsea Church','M','discus throw','Individual','Lily Burgundy','USA','NULL',95,17),
(795,'Rebekah Mojica','M','hammer throw','Individual','Tyler Olive','USA','NULL',96,35),
(796,'Annamarie Aquino','M','heptathlon','Individual','Julia Golden','USA','NULL',97,19),
(797,'Carina Tucker','M','high jump','Individual','Adrian Black','USA','NULL',98,22),
(798,'Brooklynn Whalen','M',"""Diving""",'Individual','Nina Lavender','USA','NULL',99,25);